version: '3.8'
services:
  postgis:
    image: mdillon/postgis:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: django_playground
      POSTGRES_PASSWORD: django_playground
