# Generated by Django 3.2.6 on 2021-08-24 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inline_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
