# Generated by Django 3.2.6 on 2021-08-15 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OgcService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('WMS', 'Wms'), ('WFS', 'Wfs'), ('CSW', 'Csw')], max_length=3)),
                ('origin_url', models.URLField(max_length=4096)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_identifier', models.TextField(default=uuid.uuid4)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.ogcservice')),
            ],
        ),
        migrations.CreateModel(
            name='LayerMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_identifier', models.TextField(default=uuid.uuid4)),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.layer')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='service',
            field=models.ForeignKey(help_text='the OGC Service (WMS) this layer belongs to', on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.ogcservice', verbose_name='parent service'),
        ),
        migrations.CreateModel(
            name='FeatureTypeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_identifier', models.TextField(default=uuid.uuid4)),
                ('feature_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.featuretype')),
            ],
        ),
        migrations.AddField(
            model_name='featuretype',
            name='service',
            field=models.ForeignKey(help_text='the OGC Service (WFS) this feature type belongs to', on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.ogcservice', verbose_name='parent service'),
        ),
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_identifier', models.TextField(default=uuid.uuid4)),
                ('feature_types', models.ManyToManyField(to='polymorphic_fks.FeatureType')),
                ('layers', models.ManyToManyField(to='polymorphic_fks.Layer')),
            ],
        ),
    ]
