# Generated by Django 3.2.6 on 2021-08-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('polymorphic_fks', '0003_checkrunwithgenericfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkrunwithgenericfk',
            name='resource_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'polymorphic_fks'), ('model', 'ogcservice')), models.Q(('app_label', 'polymorphic_fks'), ('model', 'layer')), models.Q(('app_label', 'polymorphic_fks'), ('model', 'featuretype')), models.Q(('app_label', 'polymorphic_fks'), ('model', 'datasetmetadata')), models.Q(('app_label', 'polymorphic_fks'), ('model', 'servicemetadata')), models.Q(('app_label', 'polymorphic_fks'), ('model', 'layermetadata')), models.Q(('app_label', 'polymorphic_fks'), ('model', 'featuretypemetadata')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
