# Generated by Django 3.2.6 on 2021-08-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polymorphic_fks', '0004_alter_checkrunwithgenericfk_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckrunWithMultipleFks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField()),
                ('dataset_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.datasetmetadata')),
                ('feature_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.featuretype')),
                ('feature_type_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.featuretypemetadata')),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.layer')),
                ('layer_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.layermetadata')),
                ('ogc_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.ogcservice')),
                ('service_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polymorphic_fks.servicemetadata')),
            ],
        ),
    ]
